"""fix scheduler models"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = '1ada7e0a421e'
down_revision: Union[str, None] = '0002_unified_runtime_hardening'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dead_letter_jobs_worker_id'), 'dead_letter_jobs', ['worker_id'], unique=False)
    op.drop_constraint(op.f('dead_letter_jobs_worker_id_fkey'), 'dead_letter_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'dead_letter_jobs', 'workers', ['worker_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_index(op.f('ix_job_logs_timestamp'), 'job_logs', ['timestamp'], unique=False)
    op.drop_constraint(op.f('job_logs_execution_id_fkey'), 'job_logs', type_='foreignkey')
    op.create_foreign_key(None, 'job_logs', 'job_executions', ['execution_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_jobs_schedule_template'), table_name='jobs')
    op.create_index(op.f('ix_jobs_parent_job_id'), 'jobs', ['parent_job_id'], unique=False)
    op.drop_constraint(op.f('jobs_parent_job_id_fkey'), 'jobs', type_='foreignkey')
    op.drop_constraint(op.f('jobs_batch_id_fkey'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'jobs', ['batch_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'jobs', 'jobs', ['parent_job_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=False)
    op.alter_column('queues', 'name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.drop_index(op.f('ix_queue_project_status'), table_name='queues')
    op.create_index(op.f('ix_queues_status'), 'queues', ['status'], unique=False)
    op.drop_column('queues', 'updated_at')
    op.drop_column('queues', 'created_at')
    op.alter_column('retry_policies', 'queue_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('uq_retry_policy_queue'), 'retry_policies', type_='unique')
    op.create_index(op.f('ix_retry_policies_queue_id'), 'retry_policies', ['queue_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retry_policies_queue_id'), table_name='retry_policies')
    op.create_unique_constraint(op.f('uq_retry_policy_queue'), 'retry_policies', ['queue_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('retry_policies', 'queue_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('queues', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('queues', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_queues_status'), table_name='queues')
    op.create_index(op.f('ix_queue_project_status'), 'queues', ['project_id', 'status'], unique=False)
    op.alter_column('queues', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_batch_id_fkey'), 'jobs', 'jobs', ['batch_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('jobs_parent_job_id_fkey'), 'jobs', 'jobs', ['parent_job_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_jobs_parent_job_id'), table_name='jobs')
    op.create_index(op.f('ix_jobs_schedule_template'), 'jobs', ['is_schedule_template'], unique=False)
    op.drop_constraint(None, 'job_logs', type_='foreignkey')
    op.create_foreign_key(op.f('job_logs_execution_id_fkey'), 'job_logs', 'job_executions', ['execution_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_job_logs_timestamp'), table_name='job_logs')
    op.drop_constraint(None, 'dead_letter_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('dead_letter_jobs_worker_id_fkey'), 'dead_letter_jobs', 'workers', ['worker_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_dead_letter_jobs_worker_id'), table_name='dead_letter_jobs')
    # ### end Alembic commands ###
